template: |
  ## What’s Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

  **RESOLVED_VERSION: v$RESOLVED_VERSION
  **PREVIOUS_TAG: v$PREVIOUS_TAG
  **INPUT_VERSION: v$INPUT_VERSION

categories:

  - title: 'Features'
    label: 'feature'
  - title: 'Bug Fixes'
    label: 'fix'
  - title: 'Maintenance'
    label: 'chore'
  - title: 'Other changes'
  - title: 'Dependency Updates'
    label: 'dependencies'
    collapse-after: 5

prerelease: true