#template: |
#  ## What’s Changed
#
#  $CHANGES
#
#  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
#  **COMPLETE: v$COMPLETE
#  **RESOLVED_VERSION: v$RESOLVED_VERSION
#  **VERSION: $MAJOR.$MINOR.$PATCH

categories:

  - title: 'Features'
    label: 'feature'
  - title: 'Bug Fixes'
    label: 'fix'
  - title: 'Maintenance'
    label: 'chore'
  - title: 'Other changes'
  - title: 'Dependency Updates'
    label: 'dependencies'
    collapse-after: 5