name: Release Draft

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: "Create release notes"
    runs-on: "ubuntu-latest"

    steps:
      - name: Set tag
        id: vars
        run: |
          echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{steps.build_changelog.outputs.changelog}}
          draft: true

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}