name: Release Draft

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: "Create release notes"
    runs-on: "ubuntu-latest"
    steps:
#
#      - name: Build Changelog
#        id: build_changelog
#        uses: mikepenz/release-changelog-builder-action@v3
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3 | cut -f 1 -d"-")
      - name: Test
        run: |
          echo ${{ steps.get_version.outputs.VERSION }}
      - name: Create release draft
        uses: softprops/action-gh-release@v1
        with:
          name: v${{ steps.get_version.outputs.VERSION }}
#          body: ${{steps.build_changelog.outputs.changelog}}
          draft: true
          generate_release_notes: true