name: Release Draft

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: "Create release notes"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - name: Set tag
        id: vars
        run: |
          echo ::set-output name=tag::${GITHUB_REF#refs/*/}
#
#      - name: Build Changelog
#        id: build_changelog
#        uses: mikepenz/release-changelog-builder-action@v3
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2
      - name: Create Release
        uses: actions/create-release@latest
        with:
          tag_name: ${{ steps.vars.outputs.tag }}
          release_name: ${{ steps.vars.outputs.tag }}
#          body: ${{steps.build_changelog.outputs.changelog}}
          draft: true
          generateReleaseNotes: true
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}